[package]
name = "rusty-audio-bridge"
version = "0.1.0"
edition = "2021"
authors = ["Simas Paulikas"]

[dependencies]
symphonia = { version = "0.5", features = ["mp3", "flac", "wav", "aac", "vorbis"] }
axum = "0.8.6"
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread"] }
