[package]
name = "rust-kv"
version = "0.1.0"
edition = "2021"
authors = ["Simas Paulikas"]

[dependencies]
axum = "0.8.6"
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread"] }
tracing-subscriber = "0.3.20"
tracing = "0.1.41"
